name = "toudi-guanli"
main = "src/worker.ts"
compatibility_date = "2024-10-09"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "qiuzhao-tracker-db"
database_id = "cc0d0c94-d524-4210-b358-f2a0257b7618"

[vars]
ENVIRONMENT = "production"